base:
  project: winequality-project
  random_state: 42 #we can use our own number 
  target_col: TARGET

data_source:
  s3_source: data_given/winequality.csv # source code

load_data:
  raw_dataset_csv: data/raw/winequality.csv # taking data from s3 source and keeping in raw data 

split_data:
  train_path: data/processed/train_winequality.csv # spliting data Train and test
  test_path: data/processed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet: # Regression parameters
    params:
      alpha: 0.88
      l1_ratio: 0.89
      # alpha: 0.9
      # l1_ratio: 0.4
model_dir: saved_models

